// SPDX-License-Identifier: BSD-3-Clause
#pragma once
#include <cstdint>

// BF16 section generated by scripts/plan_sm103_oproj.py --export-cpp; do not edit by hand.
// Independent C/R only; every physical anchor is retained, with no F/winner fitting.
// Domain: 148 SM, CUDA-reported compute capability 10.3 (sm_103a), BF16/FP32/BF16,
// CUTLASS 57e3cfb47a2d9e0d46eb6335c3dc411498efa198, CP4/8, causal rows-pull, Graph.
// Match collective/raster/resolved swizzle and actual compute budget; do not extrapolate.
// C/waves and max-slot-bytes/R are amortized services, including startup/drain.
// Aggregate slot service is NOT pure NVLink or observed aggregate payload bandwidth.
// The target queue retains its own slot imbalance; fused contention needs validation.
// policy_index: 0 = m128n256, 1 = m128n256k64e32.
// Version hashes C/R values, geometry, resources, execution identity and source evidence.
// Primitive source runs:
//   20260909-221839-e902a6
//   20260909-222035-5743d9
//   20260909-222055-93fd89
//   20260909-222113-ddce1c
//   20260909-222459-5aabaa
//   20260909-222519-74be1e
//   20260909-222544-0b3c88
//   20260909-222609-7f84b2
//   20260909-222641-d8acad
//   20260909-222700-17258a
//   20260909-222722-2835b7
//   20260909-222751-42d0cf
//   20260909-222816-090c1c
//   20260909-222834-2de9b2
//   20260909-222853-e1f012
//   20260909-222918-4e65ca
//   20260909-222944-322aa7
//   20260909-223009-d892e8
//   20260909-223057-521258
//   20260909-223123-208b49

namespace fuse::detail {

struct OprojCalibrationPoint {
  int32_t world, policy_index;
  bool along_n;
  int32_t swizzle, comm_ctas, k, reference_m, reference_n, compute_ctas;
  double tile_cycle_us, copy_slot_bandwidth_gb_s;
};

inline constexpr char kOprojCalibrationVersion[] = "8c551f5556abcea3aff309bf10b859e26e692d5c48b4773e4b4f794ed0c79cdb";
inline constexpr OprojCalibrationPoint kOprojCalibrationPoints[] = {
  {4, 0, false, 4, 8, 8192, 32768, 8192, 140, 45.667252298128808, 208.64588031234877},
  {4, 0, false, 4, 8, 16384, 32768, 8192, 140, 90.172743393202964, 183.99200048355104},
  {4, 0, false, 4, 16, 8192, 32768, 8192, 132, 44.745142497713601, 401.87836185836153},
  {4, 0, false, 4, 16, 16384, 32768, 8192, 132, 88.576506054590624, 349.86813216867421},
  {4, 0, false, 4, 24, 8192, 32768, 8192, 124, 44.294207843381969, 560.13676422128344},
  {4, 0, false, 4, 24, 16384, 32768, 8192, 124, 89.184953205621071, 522.30251923764536},
  {4, 0, false, 4, 32, 8192, 32768, 8192, 116, 43.977465428097148, 666.45016367815163},
  {4, 0, false, 4, 32, 16384, 32768, 8192, 116, 87.796735091948179, 677.67978579720761},
  {4, 0, false, 4, 48, 8192, 32768, 8192, 100, 42.342244124994046, 752.21498817998872},
  {4, 0, false, 4, 48, 16384, 32768, 8192, 100, 87.421266044058456, 802.66674161512333},
  {4, 0, false, 8, 8, 8192, 32768, 8192, 140, 45.725289037672141, 182.9157588043953},
  {4, 0, false, 8, 8, 16384, 32768, 8192, 140, 90.034985946396645, 191.31953174301208},
  {4, 0, false, 8, 16, 8192, 32768, 8192, 132, 44.990475215609109, 389.78708820820361},
  {4, 0, false, 8, 16, 16384, 32768, 8192, 132, 89.501971290225072, 356.87553069093696},
  {4, 0, false, 8, 24, 8192, 32768, 8192, 124, 44.557848973060722, 552.57649064837301},
  {4, 0, false, 8, 24, 16384, 32768, 8192, 124, 93.838328745827752, 539.45915821055235},
  {4, 0, false, 8, 32, 8192, 32768, 8192, 116, 43.33025301006478, 644.8311348498421},
  {4, 0, false, 8, 32, 16384, 32768, 8192, 116, 87.133293420496116, 662.10645421765321},
  {4, 0, false, 8, 48, 8192, 32768, 8192, 100, 43.135611022390968, 762.42450763986517},
  {4, 0, false, 8, 48, 16384, 32768, 8192, 100, 88.165853081679927, 796.0566368187441},
  {4, 0, true, 4, 8, 8192, 32768, 8192, 140, 49.754575147467143, 203.93368103723154},
  {4, 0, true, 4, 8, 16384, 32768, 8192, 140, 99.272679474394195, 176.32196436830574},
  {4, 0, true, 4, 16, 8192, 32768, 8192, 132, 48.641522725423179, 342.47603803422692},
  {4, 0, true, 4, 16, 16384, 32768, 8192, 132, 103.48342713855561, 345.60497507983712},
  {4, 0, true, 4, 24, 8192, 32768, 8192, 124, 48.255045022537459, 516.85171644834213},
  {4, 0, true, 4, 24, 16384, 32768, 8192, 124, 96.365850363204729, 504.88326897735323},
  {4, 0, true, 4, 32, 8192, 32768, 8192, 116, 47.896788153849855, 649.8011577950241},
  {4, 0, true, 4, 32, 16384, 32768, 8192, 116, 98.546928083392942, 637.20919280769044},
  {4, 0, true, 4, 48, 8192, 32768, 8192, 100, 45.912975218237904, 818.20898157505928},
  {4, 0, true, 4, 48, 16384, 32768, 8192, 100, 93.792391986381716, 797.90012231300568},
  {4, 0, true, 8, 8, 8192, 32768, 8192, 140, 46.354984833022293, 194.95243141971042},
  {4, 0, true, 8, 8, 16384, 32768, 8192, 140, 93.391725572489079, 181.4078821755329},
  {4, 0, true, 8, 16, 8192, 32768, 8192, 132, 46.905396476624503, 379.07760362688447},
  {4, 0, true, 8, 16, 16384, 32768, 8192, 132, 91.472761971609927, 350.76540955843581},
  {4, 0, true, 8, 24, 8192, 32768, 8192, 124, 45.925731089577745, 537.4193831921375},
  {4, 0, true, 8, 24, 16384, 32768, 8192, 124, 91.144120515282481, 563.2390988037788},
  {4, 0, true, 8, 32, 8192, 32768, 8192, 116, 43.996844493167501, 660.6503550497921},
  {4, 0, true, 8, 32, 16384, 32768, 8192, 116, 91.886419645497497, 659.98489217879091},
  {4, 0, true, 8, 48, 8192, 32768, 8192, 100, 43.519610311926868, 757.98128895505374},
  {4, 0, true, 8, 48, 16384, 32768, 8192, 100, 88.152583052472366, 790.18204858195736},
  {4, 1, false, 4, 8, 8192, 32768, 8192, 140, 45.773558697458043, 197.46496405680026},
  {4, 1, false, 4, 8, 16384, 32768, 8192, 140, 90.048539436469639, 177.4422176270096},
  {4, 1, false, 4, 16, 8192, 32768, 8192, 132, 45.00368284800696, 388.72141813851277},
  {4, 1, false, 4, 16, 16384, 32768, 8192, 132, 89.586795322478764, 359.20575161795779},
  {4, 1, false, 4, 24, 8192, 32768, 8192, 124, 44.108419275995509, 562.97156454679759},
  {4, 1, false, 4, 24, 16384, 32768, 8192, 124, 90.258149958368563, 529.53375839626074},
  {4, 1, false, 4, 32, 8192, 32768, 8192, 116, 44.486761093139648, 657.46594236362159},
  {4, 1, false, 4, 32, 16384, 32768, 8192, 116, 87.427152714259194, 671.98137509990886},
  {4, 1, false, 4, 48, 8192, 32768, 8192, 100, 42.088584202091866, 745.77842449551429},
  {4, 1, false, 4, 48, 16384, 32768, 8192, 100, 87.123120703348306, 802.53716910447986},
  {4, 1, false, 8, 8, 8192, 32768, 8192, 140, 45.663457805827512, 184.19094001722715},
  {4, 1, false, 8, 8, 16384, 32768, 8192, 140, 90.039867465778926, 168.21174756153496},
  {4, 1, false, 8, 16, 8192, 32768, 8192, 132, 44.934602010817756, 391.451417539999},
  {4, 1, false, 8, 16, 16384, 32768, 8192, 132, 92.966094849601618, 350.55931934578058},
  {4, 1, false, 8, 24, 8192, 32768, 8192, 124, 44.232596212358615, 547.76105733889369},
  {4, 1, false, 8, 24, 16384, 32768, 8192, 124, 88.390208002346668, 527.97659223266089},
  {4, 1, false, 8, 32, 8192, 32768, 8192, 116, 43.626815500393718, 650.2292972922337},
  {4, 1, false, 8, 32, 16384, 32768, 8192, 116, 89.64236353484678, 669.77022675366572},
  {4, 1, false, 8, 48, 8192, 32768, 8192, 100, 43.486830664844049, 762.59641901338409},
  {4, 1, false, 8, 48, 16384, 32768, 8192, 100, 86.775023762772719, 798.94429063652672},
  {4, 1, true, 4, 8, 8192, 32768, 8192, 140, 49.809896339804439, 182.80812838535613},
  {4, 1, true, 4, 8, 16384, 32768, 8192, 140, 108.41383368281994, 177.81058604189533},
  {4, 1, true, 4, 16, 8192, 32768, 8192, 132, 49.966728876507474, 363.33982121756736},
  {4, 1, true, 4, 16, 16384, 32768, 8192, 132, 102.09117616925921, 346.97733744449897},
  {4, 1, true, 4, 24, 8192, 32768, 8192, 124, 48.621373390083882, 530.05696829881072},
  {4, 1, true, 4, 24, 16384, 32768, 8192, 124, 97.336356319598295, 507.2854115251597},
  {4, 1, true, 4, 32, 8192, 32768, 8192, 116, 48.388054673100861, 660.10450590991832},
  {4, 1, true, 4, 32, 16384, 32768, 8192, 116, 99.581295335796511, 656.44164570099736},
  {4, 1, true, 4, 48, 8192, 32768, 8192, 100, 46.810926460638278, 826.44743059110431},
  {4, 1, true, 4, 48, 16384, 32768, 8192, 100, 92.872195127533701, 795.31071042099597},
  {4, 1, true, 8, 8, 8192, 32768, 8192, 140, 46.598507186113778, 212.55548230787889},
  {4, 1, true, 8, 8, 16384, 32768, 8192, 140, 101.64501707432633, 184.21337419444524},
  {4, 1, true, 8, 16, 8192, 32768, 8192, 132, 45.98857107616606, 400.44910726503588},
  {4, 1, true, 8, 16, 16384, 32768, 8192, 132, 95.335619790213443, 364.84130286070308},
  {4, 1, true, 8, 24, 8192, 32768, 8192, 124, 46.051342095901717, 544.76088575438041},
  {4, 1, true, 8, 24, 16384, 32768, 8192, 124, 93.804416371815236, 532.07872468299968},
  {4, 1, true, 8, 32, 8192, 32768, 8192, 116, 45.380055064886392, 649.42386661322041},
  {4, 1, true, 8, 32, 16384, 32768, 8192, 116, 91.617805857053938, 677.9719156543614},
  {4, 1, true, 8, 48, 8192, 32768, 8192, 100, 44.64312297541921, 757.91331965539905},
  {4, 1, true, 8, 48, 16384, 32768, 8192, 100, 88.881172784944866, 795.96560851364291},
  {8, 0, false, 4, 8, 8192, 16384, 8192, 140, 45.97973426183065, 195.91007569180573},
  {8, 0, false, 4, 8, 16384, 16384, 8192, 140, 90.639996528625488, 173.14126582170891},
  {8, 0, false, 4, 16, 8192, 16384, 8192, 132, 44.77899894118309, 363.42989105328564},
  {8, 0, false, 4, 16, 16384, 16384, 8192, 132, 88.293001055717468, 346.01472440216077},
  {8, 0, false, 4, 24, 8192, 16384, 8192, 124, 43.862588265362909, 485.77671218836582},
  {8, 0, false, 4, 24, 16384, 16384, 8192, 124, 87.80046771554386, 476.3300751385666},
  {8, 0, false, 4, 32, 8192, 16384, 8192, 116, 43.102221356497871, 552.69012106394814},
  {8, 0, false, 4, 32, 16384, 16384, 8192, 116, 87.247113386789962, 547.82745056226588},
  {8, 0, false, 4, 48, 8192, 16384, 8192, 100, 41.685854516378264, 618.91291917433171},
  {8, 0, false, 4, 48, 16384, 16384, 8192, 100, 85.594537781506048, 583.9102116475276},
  {8, 0, false, 8, 8, 8192, 16384, 8192, 140, 45.853865146636963, 193.76610389539326},
  {8, 0, false, 8, 8, 16384, 16384, 8192, 140, 90.53119818369548, 175.92081591431551},
  {8, 0, false, 8, 16, 8192, 16384, 8192, 132, 44.716000556945801, 362.42496955858968},
  {8, 0, false, 8, 16, 16384, 16384, 8192, 132, 88.808998465538025, 342.24549933532018},
  {8, 0, false, 8, 24, 8192, 16384, 8192, 124, 43.987765031702381, 488.31544153604403},
  {8, 0, false, 8, 24, 16384, 16384, 8192, 124, 87.431528989006495, 495.96055373853687},
  {8, 0, false, 8, 32, 8192, 16384, 8192, 116, 43.511112531026207, 579.82206689658756},
  {8, 0, false, 8, 32, 16384, 16384, 8192, 116, 87.399999300638839, 546.25781675041537},
  {8, 0, false, 8, 48, 8192, 16384, 8192, 100, 42.460098499205053, 653.22794212608017},
  {8, 0, false, 8, 48, 16384, 16384, 8192, 100, 85.991807100249503, 608.56206719551938},
  {8, 0, true, 4, 8, 8192, 16384, 8192, 140, 49.310934543609619, 184.88332196852917},
  {8, 0, true, 4, 8, 16384, 16384, 8192, 140, 97.778129577636719, 171.64972671843154},
  {8, 0, true, 4, 16, 8192, 16384, 8192, 132, 47.97700047492981, 342.12529548942672},
  {8, 0, true, 4, 16, 16384, 16384, 8192, 132, 95.688000321388245, 318.83724130369131},
  {8, 0, true, 4, 24, 8192, 16384, 8192, 124, 47.686587361728442, 491.08520002929208},
  {8, 0, true, 4, 24, 16384, 16384, 8192, 124, 95.31293897067799, 482.59753814199382},
  {8, 0, true, 4, 32, 8192, 16384, 8192, 116, 46.936889489491783, 605.72424803974627},
  {8, 0, true, 4, 32, 16384, 16384, 8192, 116, 94.976888762580018, 569.68476673363705},
  {8, 0, true, 4, 48, 8192, 16384, 8192, 100, 46.05268269050412, 731.96185756735304},
  {8, 0, true, 4, 48, 16384, 16384, 8192, 100, 92.82575584039455, 646.51427957330418},
  {8, 0, true, 8, 8, 8192, 16384, 8192, 140, 46.830932299296059, 196.54248363151748},
  {8, 0, true, 8, 8, 16384, 16384, 8192, 140, 93.0794636408488, 191.74838244202274},
  {8, 0, true, 8, 16, 8192, 16384, 8192, 132, 45.869000256061554, 342.72168348004357},
  {8, 0, true, 8, 16, 16384, 16384, 8192, 132, 91.683000326156616, 343.86587148279199},
  {8, 0, true, 8, 24, 8192, 16384, 8192, 124, 45.187764308031866, 492.16082187496312},
  {8, 0, true, 8, 24, 16384, 16384, 8192, 124, 90.850823065813856, 465.44684864559474},
  {8, 0, true, 8, 32, 8192, 16384, 8192, 116, 45.025779141320122, 602.39905985430414},
  {8, 0, true, 8, 32, 16384, 16384, 8192, 116, 90.811557239956329, 546.88101686295499},
  {8, 0, true, 8, 48, 8192, 16384, 8192, 100, 43.868878992592414, 669.87392713852773},
  {8, 0, true, 8, 48, 16384, 16384, 8192, 100, 89.685852934674514, 634.43351531953476},
  {8, 1, false, 4, 8, 8192, 16384, 8192, 140, 45.855998992919922, 193.82579104524839},
  {8, 1, false, 4, 8, 16384, 16384, 8192, 140, 90.271997451782227, 175.64454789194528},
  {8, 1, false, 4, 16, 8192, 16384, 8192, 132, 44.79299858212471, 369.6362921572437},
  {8, 1, false, 4, 16, 16384, 16384, 8192, 132, 88.157996535301208, 352.58102841860756},
  {8, 1, false, 4, 24, 8192, 16384, 8192, 124, 43.99623590357163, 483.93332080093529},
  {8, 1, false, 4, 24, 16384, 16384, 8192, 124, 87.359056753270764, 479.87196033158608},
  {8, 1, false, 4, 32, 8192, 16384, 8192, 116, 43.711112605200874, 548.60972198507261},
  {8, 1, false, 4, 32, 16384, 16384, 8192, 116, 87.58488628599379, 540.88645135180138},
  {8, 1, false, 4, 48, 8192, 16384, 8192, 100, 41.468879071677605, 613.08282603088128},
  {8, 1, false, 4, 48, 16384, 16384, 8192, 100, 86.392193305783152, 586.2790607307353},
  {8, 1, false, 8, 8, 8192, 16384, 8192, 140, 45.735466480255127, 194.84626316066843},
  {8, 1, false, 8, 8, 16384, 16384, 8192, 140, 90.81813494364421, 174.64260337444219},
  {8, 1, false, 8, 16, 8192, 16384, 8192, 132, 44.714998453855515, 364.65162819096258},
  {8, 1, false, 8, 16, 16384, 16384, 8192, 132, 88.618002831935883, 352.49214119743209},
  {8, 1, false, 8, 24, 8192, 16384, 8192, 124, 44.191058944253363, 492.31486006664556},
  {8, 1, false, 8, 24, 16384, 16384, 8192, 124, 88.018824072445142, 485.20109003429582},
  {8, 1, false, 8, 32, 8192, 16384, 8192, 116, 43.163554535971748, 587.54722635449184},
  {8, 1, false, 8, 32, 16384, 16384, 8192, 116, 86.842669381035705, 541.18306325795527},
  {8, 1, false, 8, 48, 8192, 16384, 8192, 100, 41.917658433681581, 662.90978905855741},
  {8, 1, false, 8, 48, 16384, 16384, 8192, 100, 86.524096930899276, 606.98909179188763},
  {8, 1, true, 4, 8, 8192, 16384, 8192, 140, 49.357867240905762, 176.69981820627527},
  {8, 1, true, 4, 8, 16384, 16384, 8192, 140, 101.81439717610677, 174.26890625358644},
  {8, 1, true, 4, 16, 8192, 16384, 8192, 132, 48.124000430107117, 340.80330321314591},
  {8, 1, true, 4, 16, 16384, 16384, 8192, 132, 96.928998827934265, 325.29744193155562},
  {8, 1, true, 4, 24, 8192, 16384, 8192, 124, 47.75811644161449, 491.46881735725043},
  {8, 1, true, 4, 24, 16384, 16384, 8192, 124, 100.23811985464657, 475.09873233557448},
  {8, 1, true, 4, 32, 8192, 16384, 8192, 116, 47.379556629392837, 612.68481333391878},
  {8, 1, true, 4, 32, 16384, 16384, 8192, 116, 95.570663611094162, 561.33618206489814},
  {8, 1, true, 4, 48, 8192, 16384, 8192, 100, 46.388291731113341, 731.39454647475793},
  {8, 1, true, 4, 48, 16384, 16384, 8192, 100, 93.783413491597983, 645.69952039830821},
  {8, 1, true, 8, 8, 8192, 16384, 8192, 140, 47.002665201822914, 190.7156753836714},
  {8, 1, true, 8, 8, 16384, 16384, 8192, 140, 96.505602200826004, 176.28681546940405},
  {8, 1, true, 8, 16, 8192, 16384, 8192, 132, 46.367999166250229, 341.16058515634398},
  {8, 1, true, 8, 16, 16384, 16384, 8192, 132, 91.675996780395508, 339.22834864645318},
  {8, 1, true, 8, 24, 8192, 16384, 8192, 124, 44.980704784393311, 486.40265919840283},
  {8, 1, true, 8, 24, 16384, 16384, 8192, 124, 90.88658585267909, 462.40463272834756},
  {8, 1, true, 8, 32, 8192, 16384, 8192, 116, 44.90755663977729, 599.37652920458345},
  {8, 1, true, 8, 32, 16384, 16384, 8192, 116, 91.049777136908631, 565.80386813217069},
  {8, 1, true, 8, 48, 8192, 16384, 8192, 100, 45.211318062572943, 671.92480945078},
  {8, 1, true, 8, 48, 16384, 16384, 8192, 100, 88.523707738736775, 634.24312908437685},
};

}  // namespace fuse::detail

// BEGIN MXFP8 QKV CALIBRATION
// This independent section is preserved by the BF16 exporter. Populate it only
// from audited primitive services, never from fused winners or invented timing.
#include <array>

namespace fuse::detail {

// Directly measured compute tile intervals at this exact resource budget.
// Publication/TMA context diagnostics remain in the audited calibration JSON;
// they are not decision coefficients and do not enter the production header.
struct Mxfp8QkvServices {
  double startup_us = 0, tile_first_us = 0, tile_cycle_us = 0;
};

// Whole local service spans measured with output ready. They include all
// worker publications/drains but exclude cross-rank finalization. These are
// workload services, not instruction latencies or bounds on fused contention.
struct Mxfp8QkvBulkServices {
  int64_t reference_m = 0;
  double route_us = 0, quant_route_us = 0;
};

struct Mxfp8QkvCalibrationPoint {
  int32_t world = 0, sm_count = 148, capability = 103;
  int32_t tile_m = 128, tile_n = 256, tile_k = 128, epilogue_n = 64;
  int32_t stages = 0, cluster_ctas = 1, raster = 0, swizzle = 1;
  int32_t comm_ctas = 0, compute_ctas = 0, k = 0, dynamic_smem_bytes = 0;
  int32_t q_heads = 0, kv_heads = 0, head_dim = 128;
  // Applicability is an explicitly measured physical workload domain. In
  // particular, a service observed at one N does not authorize every N.
  int64_t m_min = 0, m_max = 0, n_min = 0, n_max = 0;
  // Zero means exact K only. A nonzero identifier explicitly authorizes linear
  // interpolation between K anchors with identical domain and physical keys.
  uint64_t k_interpolation_group = 0;
  Mxfp8QkvServices services{};
  Mxfp8QkvBulkServices bulk{};
};

// Generated by scripts/plan_sm103_mxfp8.py; direct intervals, no F fitting.
// VALIDATION PENDING: S128K calibration; S256K and S512K are holdouts.
// Whole local R/QR services; fixed W plus incremental output, not DMA latency.
inline constexpr char kMxfp8QkvCalibrationVersion[] = "validation_pending_6714eeeb1628e94a8c7dbebd31c67233a47df1bde3f9e9a87d9553aea44e0eb8";
inline constexpr std::array<Mxfp8QkvCalibrationPoint, 57> kMxfp8QkvCalibrationPoints = [] {
  std::array<Mxfp8QkvCalibrationPoint, 57> points{};
  // 20260911-200407-2691e9; sparse_separate
  {
    auto& p = points[0];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 2048;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 16;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 4096; p.n_max = 4096;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.6639999999999999;
    p.services.tile_first_us = 13.410424242424241;
    p.services.tile_cycle_us = 6.8227971745711402;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 386.62400000000002;
    p.bulk.quant_route_us = 443.93599999999998;
  }
  // 20260911-200423-9845fc; sparse_separate
  {
    auto& p = points[1];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 2048;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 16;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 4096; p.n_max = 4096;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.5680000000000001;
    p.services.tile_first_us = 13.584275862068965;
    p.services.tile_cycle_us = 6.666154773869347;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 343.19999999999999;
    p.bulk.quant_route_us = 369.60000000000002;
  }
  // 20260911-200439-2d3a29; every_chunk_included
  {
    auto& p = points[2];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 2048;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 16;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 4096; p.n_max = 4096;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.6000000000000001;
    p.services.tile_first_us = 13.102476190476191;
    p.services.tile_cycle_us = 6.4631385842472584;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 316.67200000000003;
    p.bulk.quant_route_us = 321.56799999999998;
  }
  // 20260911-200455-8f1ed4; sparse_separate
  {
    auto& p = points[3];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 2048;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 16;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 4096; p.n_max = 4096;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.5680000000000001;
    p.services.tile_first_us = 13.07369696969697;
    p.services.tile_cycle_us = 6.7939874739039672;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 192.864;
    p.bulk.quant_route_us = 257.60000000000002;
  }
  // 20260911-200515-b69cc9; sparse_separate
  {
    auto& p = points[4];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 2048;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 16;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 4096; p.n_max = 4096;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.5680000000000001;
    p.services.tile_first_us = 13.116965517241379;
    p.services.tile_cycle_us = 6.6478840579710141;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 188.31999999999999;
    p.bulk.quant_route_us = 211.96799999999999;
  }
  // 20260911-200535-92900d; every_chunk_included
  {
    auto& p = points[5];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 2048;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 16;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 4096; p.n_max = 4096;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.5680000000000001;
    p.services.tile_first_us = 12.899428571428571;
    p.services.tile_cycle_us = 6.4119755600814656;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 179.00800000000001;
    p.bulk.quant_route_us = 191.71199999999999;
  }
  // 20260911-200555-d89be3; sparse_separate
  {
    auto& p = points[6];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 2048;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 16;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 1;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 4096; p.n_max = 4096;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.536;
    p.services.tile_first_us = 12.481212121212122;
    p.services.tile_cycle_us = 6.6712651356993735;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 193.536;
    p.bulk.quant_route_us = 254.464;
  }
  // 20260911-200615-745542; sparse_separate
  {
    auto& p = points[7];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 2048;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 16;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 1;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 4096; p.n_max = 4096;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.536;
    p.services.tile_first_us = 12.368275862068966;
    p.services.tile_cycle_us = 6.4584016563146998;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 193.15199999999999;
    p.bulk.quant_route_us = 209.12;
  }
  // 20260911-200641-aca121; every_chunk_included
  {
    auto& p = points[8];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 2048;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 16;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 1;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 4096; p.n_max = 4096;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.5680000000000001;
    p.services.tile_first_us = 12.452952380952382;
    p.services.tile_cycle_us = 6.2370183299389002;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 175.904;
    p.bulk.quant_route_us = 183.55199999999999;
  }
  // 20260911-200701-ba6f8e; sparse_separate
  {
    auto& p = points[9];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 4096;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 4;
    p.head_dim = 128;
    p.swizzle = 2;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 9216; p.n_max = 9216;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.792;
    p.services.tile_first_us = 22.355878787878787;
    p.services.tile_cycle_us = 12.963899603698811;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 875.29600000000005;
    p.bulk.quant_route_us = 1058.6559999999999;
  }
  // 20260911-200725-f2f193; sparse_separate
  {
    auto& p = points[10];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 4096;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 4;
    p.head_dim = 128;
    p.swizzle = 2;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 9216; p.n_max = 9216;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.696;
    p.services.tile_first_us = 20.845517241379312;
    p.services.tile_cycle_us = 12.134421098901099;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 743.87199999999996;
    p.bulk.quant_route_us = 785.82399999999996;
  }
  // 20260911-200749-ba50b6; sparse_separate
  {
    auto& p = points[11];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 4096;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 4;
    p.head_dim = 128;
    p.swizzle = 2;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 9216; p.n_max = 9216;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.5680000000000001;
    p.services.tile_first_us = 17.175999999999998;
    p.services.tile_cycle_us = 11.382945247481384;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 661.27999999999997;
    p.bulk.quant_route_us = 715.87199999999996;
  }
  // 20260911-200813-06cbfa; sparse_separate
  {
    auto& p = points[12];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.016;
    p.services.tile_first_us = 39.398545454545456;
    p.services.tile_cycle_us = 26.525432528690146;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 1003.3920000000001;
    p.bulk.quant_route_us = 1375.9359999999999;
  }
  // 20260911-200843-4ccb86; sparse_separate
  {
    auto& p = points[13];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.952;
    p.services.tile_first_us = 37.22510344827586;
    p.services.tile_cycle_us = 24.866696167522718;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 989.53599999999994;
    p.bulk.quant_route_us = 1112.288;
  }
  // 20260911-200914-c3fd0b; sparse_separate
  {
    auto& p = points[14];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.6319999999999999;
    p.services.tile_first_us = 31.54247619047619;
    p.services.tile_cycle_us = 22.248834974399372;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 894.43200000000002;
    p.bulk.quant_route_us = 1025.6320000000001;
  }
  // 20260911-200945-9f825d; sparse_separate
  {
    auto& p = points[15];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.984;
    p.services.tile_first_us = 40.432242424242425;
    p.services.tile_cycle_us = 28.227897111199049;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 976.54399999999998;
    p.bulk.quant_route_us = 1345.3440000000001;
  }
  // 20260911-201016-6906ce; sparse_separate
  {
    auto& p = points[16];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.728;
    p.services.tile_first_us = 35.787034482758621;
    p.services.tile_cycle_us = 25.799010667720268;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 809.24800000000005;
    p.bulk.quant_route_us = 872.25599999999997;
  }
  // 20260911-201048-183fcd; sparse_separate
  {
    auto& p = points[17];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.6319999999999999;
    p.services.tile_first_us = 32.080380952380956;
    p.services.tile_cycle_us = 23.907481685703029;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 736.06399999999996;
    p.bulk.quant_route_us = 812.54399999999998;
  }
  // 20260911-201119-3db9cc; sparse_separate
  {
    auto& p = points[18];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8879999999999999;
    p.services.tile_first_us = 37.426666666666662;
    p.services.tile_cycle_us = 25.024070569366479;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 556.63999999999999;
    p.bulk.quant_route_us = 1289.0239999999999;
  }
  // 20260911-201148-6cb23e; sparse_separate
  {
    auto& p = points[19];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.6639999999999999;
    p.services.tile_first_us = 35.609655172413788;
    p.services.tile_cycle_us = 23.983609912070342;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 582.048;
    p.bulk.quant_route_us = 897.47199999999998;
  }
  // 20260911-201219-9c65b3; sparse_separate
  {
    auto& p = points[20];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.504;
    p.services.tile_first_us = 30.800000000000001;
    p.services.tile_cycle_us = 22.058630659253378;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 605.53599999999994;
    p.bulk.quant_route_us = 759.29600000000005;
  }
  // 20260911-201248-531069; sparse_separate
  {
    auto& p = points[21];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.76;
    p.services.tile_first_us = 38.005575757575762;
    p.services.tile_cycle_us = 26.980740978348035;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 495.13600000000002;
    p.bulk.quant_route_us = 1076.672;
  }
  // 20260911-201318-a47964; sparse_separate
  {
    auto& p = points[22];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.6000000000000001;
    p.services.tile_first_us = 35.287999999999997;
    p.services.tile_cycle_us = 25.526586730615509;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 459.29599999999999;
    p.bulk.quant_route_us = 714.91200000000003;
  }
  // 20260911-201347-3aa87e; sparse_separate
  {
    auto& p = points[23];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 8192;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 64;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 10240; p.n_max = 10240;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.472;
    p.services.tile_first_us = 31.907428571428571;
    p.services.tile_cycle_us = 23.726551231135822;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 430.20800000000003;
    p.bulk.quant_route_us = 585.27999999999997;
  }
  // 20260911-201415-0df32d; sparse_separate
  {
    auto& p = points[24];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.984;
    p.services.tile_first_us = 70.976969696969689;
    p.services.tile_cycle_us = 56.236014863387979;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 1825.2159999999999;
    p.bulk.quant_route_us = 3916.1599999999999;
  }
  // 20260911-201713-b31a53; sparse_separate
  {
    auto& p = points[25];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8560000000000001;
    p.services.tile_first_us = 65.566344827586207;
    p.services.tile_cycle_us = 51.959711727451406;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 1807.296;
    p.bulk.quant_route_us = 2733.6640000000002;
  }
  // 20260911-201812-735451; sparse_separate
  {
    auto& p = points[26];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.76;
    p.services.tile_first_us = 60.408380952380952;
    p.services.tile_cycle_us = 48.802476564203182;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 1627.712;
    p.bulk.quant_route_us = 2148.672;
  }
  // 20260911-201916-43579b; sparse_separate
  {
    auto& p = points[27];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.1440000000000001;
    p.services.tile_first_us = 74.74739393939393;
    p.services.tile_cycle_us = 58.197342076502736;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 1750.72;
    p.bulk.quant_route_us = 3764.3519999999999;
  }
  // 20260911-202014-ca3406; sparse_separate
  {
    auto& p = points[28];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.9199999999999999;
    p.services.tile_first_us = 70.237793103448269;
    p.services.tile_cycle_us = 54.188343306398778;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 1446.336;
    p.bulk.quant_route_us = 2272.4479999999999;
  }
  // 20260911-202112-b92825; sparse_separate
  {
    auto& p = points[29];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.728;
    p.services.tile_first_us = 56.665142857142854;
    p.services.tile_cycle_us = 46.752755177676036;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 1316.8320000000001;
    p.bulk.quant_route_us = 1837.3119999999999;
  }
  // 20260911-202215-2db0fb; sparse_separate
  {
    auto& p = points[30];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.016;
    p.services.tile_first_us = 70.289212121212131;
    p.services.tile_cycle_us = 55.709523557904006;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 925.88800000000003;
    p.bulk.quant_route_us = 3292.5439999999999;
  }
  // 20260911-202304-902333; sparse_separate
  {
    auto& p = points[31];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8560000000000001;
    p.services.tile_first_us = 65.679448275862072;
    p.services.tile_cycle_us = 51.727535824175824;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 850.68799999999999;
    p.bulk.quant_route_us = 2061.2800000000002;
  }
  // 20260911-202354-daa8ad; sparse_separate
  {
    auto& p = points[32];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.696;
    p.services.tile_first_us = 55.067428571428572;
    p.services.tile_cycle_us = 45.052713096802449;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 804.48000000000002;
    p.bulk.quant_route_us = 1430.336;
  }
  // 20260911-202449-fc6dfa; sparse_separate
  {
    auto& p = points[33];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.0800000000000001;
    p.services.tile_first_us = 73.221090909090918;
    p.services.tile_cycle_us = 57.767281373844121;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 890.11199999999997;
    p.bulk.quant_route_us = 3291.0079999999998;
  }
  // 20260911-202539-baf064; sparse_separate
  {
    auto& p = points[34];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8240000000000001;
    p.services.tile_first_us = 66.506758620689652;
    p.services.tile_cycle_us = 52.629387252747257;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 825.85599999999999;
    p.bulk.quant_route_us = 1973.056;
  }
  // 20260911-202633-112adb; sparse_separate
  {
    auto& p = points[35];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 16384;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 128;
    p.kv_heads = 8;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 18432; p.n_max = 18432;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.6000000000000001;
    p.services.tile_first_us = 56.884571428571427;
    p.services.tile_cycle_us = 46.842456416995184;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 764.76800000000003;
    p.bulk.quant_route_us = 1402.432;
  }
  // 20260911-202728-d9f70f; sparse_separate
  {
    auto& p = points[36];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.1120000000000001;
    p.services.tile_first_us = 38.468606060606064;
    p.services.tile_cycle_us = 24.585522813895242;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 3631.2640000000001;
    p.bulk.quant_route_us = 5934.0159999999996;
  }
  // 20260911-202829-89b757; sparse_separate
  {
    auto& p = points[37];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8560000000000001;
    p.services.tile_first_us = 34.330206896551722;
    p.services.tile_cycle_us = 22.283641667573747;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 3548.6399999999999;
    p.bulk.quant_route_us = 3721.2800000000002;
  }
  // 20260911-202931-36d44c; sparse_separate
  {
    auto& p = points[38];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.696;
    p.services.tile_first_us = 31.124190476190478;
    p.services.tile_cycle_us = 20.614715823817292;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 3064.5439999999999;
    p.bulk.quant_route_us = 3474.8159999999998;
  }
  // 20260911-203040-9ea21b; sparse_separate
  {
    auto& p = points[39];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.016;
    p.services.tile_first_us = 36.663030303030304;
    p.services.tile_cycle_us = 25.603833169988022;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 3505.1840000000002;
    p.bulk.quant_route_us = 4651.8720000000003;
  }
  // 20260911-203142-a38471; sparse_separate
  {
    auto& p = points[40];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8879999999999999;
    p.services.tile_first_us = 34.629241379310351;
    p.services.tile_cycle_us = 23.967310329813866;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 2889.4400000000001;
    p.bulk.quant_route_us = 3207.2640000000001;
  }
  // 20260911-203243-99d796; sparse_separate
  {
    auto& p = points[41];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.696;
    p.services.tile_first_us = 31.470095238095237;
    p.services.tile_cycle_us = 21.898204676454597;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 2571.5839999999998;
    p.bulk.quant_route_us = 2946.7199999999998;
  }
  // 20260911-203351-de80a1; sparse_separate
  {
    auto& p = points[42];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.1440000000000001;
    p.services.tile_first_us = 37.042181818181817;
    p.services.tile_cycle_us = 24.671506885245901;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 1951.232;
    p.bulk.quant_route_us = 3529.0880000000002;
  }
  // 20260911-203441-0fb995; sparse_separate
  {
    auto& p = points[43];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8560000000000001;
    p.services.tile_first_us = 37.185379310344828;
    p.services.tile_cycle_us = 23.42859488971391;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 1881.664;
    p.bulk.quant_route_us = 2720.1599999999999;
  }
  // 20260911-203531-2b9894; sparse_separate
  {
    auto& p = points[44];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.6319999999999999;
    p.services.tile_first_us = 28.625142857142858;
    p.services.tile_cycle_us = 19.992572051449748;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 1696.896;
    p.bulk.quant_route_us = 2254.848;
  }
  // 20260911-203628-61135e; sparse_separate
  {
    auto& p = points[45];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.1440000000000001;
    p.services.tile_first_us = 37.43030303030303;
    p.services.tile_cycle_us = 25.622071256830601;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 1760.5119999999999;
    p.bulk.quant_route_us = 3516.3519999999999;
  }
  // 20260911-203718-b63d12; sparse_separate
  {
    auto& p = points[46];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.792;
    p.services.tile_first_us = 33.856000000000002;
    p.services.tile_cycle_us = 23.800780956540731;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 1622.816;
    p.bulk.quant_route_us = 2439.4560000000001;
  }
  // 20260911-203808-b59284; sparse_separate
  {
    auto& p = points[47];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 7168;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 96;
    p.kv_heads = 96;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 36864; p.n_max = 36864;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.9199999999999999;
    p.services.tile_first_us = 31.600380952380956;
    p.services.tile_cycle_us = 21.783138434706778;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 1520.576;
    p.bulk.quant_route_us = 2027.6800000000001;
  }
  // 20260911-203904-f4cf58; sparse_separate
  {
    auto& p = points[48];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 14336;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 112;
    p.kv_heads = 112;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 43008; p.n_max = 43008;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.016;
    p.services.tile_first_us = 66.368727272727284;
    p.services.tile_cycle_us = 49.785856889635227;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 4354.8800000000001;
    p.bulk.quant_route_us = 8948.2240000000002;
  }
  // 20260911-204052-925105; sparse_separate
  {
    auto& p = points[49];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 14336;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 112;
    p.kv_heads = 112;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 43008; p.n_max = 43008;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8879999999999999;
    p.services.tile_first_us = 61.756137931034488;
    p.services.tile_cycle_us = 45.958865988995619;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 3769.6640000000002;
    p.bulk.quant_route_us = 5682.3999999999996;
  }
  // 20260911-204236-9a986a; sparse_separate
  {
    auto& p = points[50];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 14336;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 112;
    p.kv_heads = 112;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 43008; p.n_max = 43008;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8240000000000001;
    p.services.tile_first_us = 56.233904761904761;
    p.services.tile_cycle_us = 41.104486813903641;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 3524.576;
    p.bulk.quant_route_us = 4388.1279999999997;
  }
  // 20260911-204425-2a8a78; sparse_separate
  {
    auto& p = points[51];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 14336;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 112;
    p.kv_heads = 112;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 43008; p.n_max = 43008;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.952;
    p.services.tile_first_us = 64.370424242424235;
    p.services.tile_cycle_us = 49.301041362530412;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 2472.5439999999999;
    p.bulk.quant_route_us = 6869.6319999999996;
  }
  // 20260911-204546-502548; sparse_separate
  {
    auto& p = points[52];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 14336;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 112;
    p.kv_heads = 112;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 43008; p.n_max = 43008;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8879999999999999;
    p.services.tile_first_us = 60.939034482758622;
    p.services.tile_cycle_us = 45.544038900317936;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 2376.8000000000002;
    p.bulk.quant_route_us = 4719.4560000000001;
  }
  // 20260911-204711-ccf4ec; sparse_separate
  {
    auto& p = points[53];
    p.world = 8;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 0;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 14336;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 112;
    p.kv_heads = 112;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 16384; p.m_max = 65536;
    p.n_min = 43008; p.n_max = 43008;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8240000000000001;
    p.services.tile_first_us = 55.107809523809529;
    p.services.tile_cycle_us = 41.18488440709617;
    p.bulk.reference_m = 16384;
    p.bulk.route_us = 2072.192;
    p.bulk.quant_route_us = 3390.2080000000001;
  }
  // 20260911-204956-50e1c8; sparse_separate
  {
    auto& p = points[54];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 16;
    p.compute_ctas = 132;
    p.k = 14336;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 112;
    p.kv_heads = 112;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 43008; p.n_max = 43008;
    p.k_interpolation_group = 0;
    p.services.startup_us = 2.016;
    p.services.tile_first_us = 67.594666666666669;
    p.services.tile_cycle_us = 50.668004851198809;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 4099.9359999999997;
    p.bulk.quant_route_us = 7979.9040000000005;
  }
  // 20260911-205138-7c73ed; sparse_separate
  {
    auto& p = points[55];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 32;
    p.compute_ctas = 116;
    p.k = 14336;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 112;
    p.kv_heads = 112;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 43008; p.n_max = 43008;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.8879999999999999;
    p.services.tile_first_us = 61.755586206896552;
    p.services.tile_cycle_us = 46.060709129907679;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 3363.5839999999998;
    p.bulk.quant_route_us = 5015.1360000000004;
  }
  // 20260911-205327-d17519; sparse_separate
  {
    auto& p = points[56];
    p.world = 4;
    p.sm_count = 148;
    p.capability = 103;
    p.tile_m = 128;
    p.tile_n = 256;
    p.tile_k = 128;
    p.epilogue_n = 32;
    p.stages = 4;
    p.cluster_ctas = 1;
    p.raster = 1;
    p.comm_ctas = 64;
    p.compute_ctas = 84;
    p.k = 14336;
    p.dynamic_smem_bytes = 220160;
    p.q_heads = 112;
    p.kv_heads = 112;
    p.head_dim = 128;
    p.swizzle = 8;
    p.m_min = 32768; p.m_max = 131072;
    p.n_min = 43008; p.n_max = 43008;
    p.k_interpolation_group = 0;
    p.services.startup_us = 1.76;
    p.services.tile_first_us = 56.96076190476191;
    p.services.tile_cycle_us = 42.385262883235491;
    p.bulk.reference_m = 32768;
    p.bulk.route_us = 3037.8240000000001;
    p.bulk.quant_route_us = 4048.1280000000002;
  }
  return points;
}();

}  // namespace fuse::detail
// END MXFP8 QKV CALIBRATION
